package com.sindhueventpay.models;

import com.sindhueventpay.enums.RegistrationStatus;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity for the {@code registrations} table.
 *
 * <p><strong>Primary key design:</strong> the PK is a UUID string (CHAR 36)
 * generated in Java before persistence. This decouples the public-facing
 * identifier from database internals and prevents sequential enumeration.
 *
 * <p><strong>Registration number:</strong> the human-readable event-specific
 * number (e.g. {@code EVT2026-000042}) is stored in {@code registrationNumber}
 * and is {@code null} until the payment is verified and the status is
 * transitioned to {@link RegistrationStatus#PAID}.
 *
 * <p><strong>Aadhaar document:</strong> the S3 object key is stored here, never
 * a public URL. Access requires a short-lived pre-signed URL generated by an
 * authorised admin endpoint.
 */
@Entity
@Table(name = "registrations")
@Getter
@Setter
public class Registration {

    /** UUID primary key — never exposed as a sequential number. */
    @Id
    @Column(name = "id", length = 36, nullable = false, updatable = false)
    private String id;

    /** FK to the event this registration belongs to. */
    @Column(name = "event_id", nullable = false)
    private Long eventId;

    /**
     * Human-readable registration number, e.g. {@code EVT2026-000042}.
     * Null until status transitions to {@link RegistrationStatus#PAID}.
     * Has a UNIQUE constraint — generated atomically under a DB-level lock.
     */
    @Column(name = "registration_number", length = 50, unique = true)
    private String registrationNumber;

    @Column(name = "full_name", nullable = false, length = 100)
    private String fullName;

    @Column(name = "email", nullable = false, length = 150)
    private String email;

    @Column(name = "mobile_number", nullable = false, length = 15)
    private String mobileNumber;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    private RegistrationStatus status = RegistrationStatus.PENDING_PAYMENT;

    /**
     * AWS S3 object key for the Aadhaar document.
     * Pattern: {@code events/{eventCode}/registrations/{uuid}/aadhaar/document.{ext}}
     * Never a public URL. Access requires a presigned URL from an authorised endpoint.
     * Sensitive: never log this value.
     */
    @Column(name = "aadhaar_s3_key", length = 500)
    private String aadhaarS3Key;

    /**
     * Razorpay order ID set at registration creation.
     * Unique per registration — used to look up this record from payment callbacks.
     */
    @Column(name = "razorpay_order_id", nullable = false, length = 100, unique = true)
    private String razorpayOrderId;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Auto-generates the UUID before the entity is first persisted. */
    @PrePersist
    private void generateId() {
        if (this.id == null) {
            this.id = UUID.randomUUID().toString();
        }
    }
}
